# Generated by Django 3.2.7 on 2021-09-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('english', 'english'), ('science', 'science'), ('history', 'history'), ('math', 'math')], max_length=60)),
                ('coursenumber', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('instructorname', models.TextField(blank=True, default='', max_length=300)),
                ('duration', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
